<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL.csproj" />
    <ProjectReference Include="..\..\..\DataBaseDll\DataBaseManager\DataBaseManager\DataBaseManager.csproj" />
    <ProjectReference Include="..\..\..\ExceptionsDll\Exceptions\Exceptions\Exceptions.csproj" />
    <ProjectReference Include="..\..\..\ItemsDll\Items\Items\Items.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AutoPartsManagementDLL">
      <HintPath>..\..\..\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL\bin\Release\net8.0\AutoPartsManagementDLL.dll</HintPath>
    </Reference>
    <Reference Include="DataBaseManager">
      <HintPath>..\..\..\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL\bin\Release\net8.0\DataBaseManager.dll</HintPath>
    </Reference>
    <Reference Include="Exceptions">
      <HintPath>..\..\..\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL\bin\Release\net8.0\Exceptions.dll</HintPath>
    </Reference>
    <Reference Include="Items">
      <HintPath>..\..\..\AutoPartsManagementDLL\AutoPartsManagementDLL\AutoPartsManagementDLL\bin\Release\net8.0\Items.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>