<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\DataBaseDll\DataBaseManager\DataBaseManager\DataBaseManager.csproj" />
    <ProjectReference Include="..\..\..\ExceptionsDll\Exceptions\Exceptions\Exceptions.csproj" />
    <ProjectReference Include="..\..\..\ItemsDll\Items\Items\Items.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DataBaseManager">
      <HintPath>..\..\..\DataBaseDll\DataBaseManager\DataBaseManager\bin\Release\net8.0\DataBaseManager.dll</HintPath>
    </Reference>
    <Reference Include="Exceptions">
      <HintPath>..\..\..\ExceptionsDll\Exceptions\Exceptions\bin\Release\net8.0\Exceptions.dll</HintPath>
    </Reference>
    <Reference Include="Items">
      <HintPath>..\..\..\ItemsDll\Items\Items\bin\Release\net8.0\Items.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
